# Generated by Django 3.1.6 on 2021-02-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=150)),
            ],
        ),
    ]
