# Generated by Django 3.1.6 on 2021-02-23 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PontosTuristicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='Api_IloveMarajo')),
                ('nome_Ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PontosTuristicos.pontosturisticos')),
            ],
        ),
    ]
