# Generated by Django 3.1.6 on 2021-02-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0002_remove_fotos_nome_ponto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos',
            name='nome_ponto',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
