# Generated by Django 3.1.6 on 2021-02-16 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Municipios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontosTuristicos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=150)),
                ('perfil', models.ImageField(blank=True, null=True, upload_to='Api_IloveMarajo')),
                ('descricao', models.TextField(max_length=500)),
                ('cidade', models.TextField(max_length=150)),
                ('latitude', models.TextField(max_length=100)),
                ('longitude', models.TextField(max_length=100)),
                ('estrelas', models.TextField(max_length=12)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Municipios.municipios')),
            ],
        ),
    ]
