# Generated by Django 3.1.6 on 2021-02-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0002_remove_fotos_nome_ponto'),
        ('PontosTuristicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='fotos',
            field=models.ManyToManyField(to='fotos.Fotos'),
        ),
    ]
